[package]
name = "my_game"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
macroquad-particles = "0.2.2"

[patch.crates-io]
macroquad = { git = "https://github.com/not-fl3/macroquad" }
macroquad-particles = { git = "https://github.com/not-fl3/macroquad" }
